config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'artists#index'

  resources :artists
  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates_presence_of :name
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    if params[:order_by] == 'created_at'
      @artists = Artist.all.order(:created_at)
    elsif params[:order_by] == 'name'
      @artists = Artist.all.order(:name)
    else
      @artists = Artist.all
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    @song = Song.new
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to root_path, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @songs = Song.all
    @song = Song.find(params[:id])
    @song.update_attributes(song_params)
  end

  def destroy
    @songs = Song.all
    @song = Song.find(params[:id])
    @song.destroy
  end

  def delete
    @song = Song.find(params[:song_id])
    @songs = Song.all
  end

  private
    def song_params
      params.require(:song).permit(:name)
    end
  end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
  end

  def create
    @song = Song.create(song_params)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
  end

  def destroy
    @songs = Song.all
    @song = Song.find(params[:id])
    @song.destroy
  end

  private

  def song_params
    params.require(:song).permit(:name, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@song, method: 'post', remote: true, class: 'form') do |f| %>
  <div class="form-group <%= @song.errors.any? ? 'has-error' : '' %>" id="formgroup-title">
    <%= f.text_field :name, placeholder: "What to add?", class: 'song-title' %>
    <%= f.hidden_field :artist_id, value: @artist.id %>
    <% if @song.errors.any? %>
      <% @song.errors.full_messages.each do |message| %>
        <span class="help-block"><%= message %></span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/artists/_song.html.erb
<ul class="songList">
<% @artist.songs.each do |song| %>
  <li class="song"><%= song.name %></li>

  <%= link_to "Delete", song ,:method => 'delete' %>
<% end %>

</ul>

app/views/artists/create.js.erb
$("#song")("<%= j render(partial: 'song') %>")

app/views/artists/index.html.erb
<h1>All artists</h1>

<%= link_to('Order by name', :order_by => 'name') %>
<%= link_to('Order by date', :order_by => 'created_at') %>

<ul>
  <% @artists.each do |artist| %>
  <li><img src="<%= artist.image %>"/><%= link_to artist.name, artist_path(artist.id) %></li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<%= render 'song' %>

<%= render 'form', remote: true; %>

<%= link_to "Back to homepage", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song, remote: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit "Create" %>
<% end %>

app/views/songs/create.js.erb
$('.song').append('<%= j render(@song) %>')